# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ripple}
  s.version = "0.4.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Cribbs"]
  s.date = %q{2010-03-01}
  s.description = %q{ripple is a rich Ruby client for Riak, Basho's distributed database.  It includes all the basics of accessing and manipulating Riak buckets and objects, and an object mapper library for building a rich domain on top of Riak.}
  s.email = %q{seancribbs@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CONTRIBUTORS.textile",
     "LICENSE",
     "README.textile",
     "RELEASE_NOTES.textile",
     "Rakefile",
     "VERSION",
     "lib/riak.rb",
     "lib/riak/bucket.rb",
     "lib/riak/client.rb",
     "lib/riak/client/curb_backend.rb",
     "lib/riak/client/http_backend.rb",
     "lib/riak/client/net_http_backend.rb",
     "lib/riak/failed_request.rb",
     "lib/riak/i18n.rb",
     "lib/riak/invalid_response.rb",
     "lib/riak/link.rb",
     "lib/riak/locale/en.yml",
     "lib/riak/map_reduce.rb",
     "lib/riak/map_reduce_error.rb",
     "lib/riak/robject.rb",
     "lib/riak/util/activesupporthelper.rb",
     "lib/riak/util/fiber1.8.rb",
     "lib/riak/util/headers.rb",
     "lib/riak/util/multipart.rb",
     "lib/riak/util/translation.rb",
     "lib/riak/walk_spec.rb",
     "ripple.gemspec",
     "spec/fixtures/cat.jpg",
     "spec/fixtures/multipart-blank.txt",
     "spec/fixtures/multipart-with-body.txt",
     "spec/riak/bucket_spec.rb",
     "spec/riak/client_spec.rb",
     "spec/riak/curb_backend_spec.rb",
     "spec/riak/headers_spec.rb",
     "spec/riak/http_backend_spec.rb",
     "spec/riak/link_spec.rb",
     "spec/riak/map_reduce_spec.rb",
     "spec/riak/multipart_spec.rb",
     "spec/riak/net_http_backend_spec.rb",
     "spec/riak/object_spec.rb",
     "spec/riak/walk_spec_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/http_backend_implementation_examples.rb",
     "spec/support/mock_server.rb",
     "test.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://seancribbs.github.com/ripple}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["`gem install curb` for better HTTP performance", "`gem install curb` for better HTTP performance"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{ripple is a rich Ruby client for Riak, Basho's distributed database.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/support/mock_server.rb",
     "spec/support/http_backend_implementation_examples.rb",
     "spec/riak/http_backend_spec.rb",
     "spec/riak/curb_backend_spec.rb",
     "spec/riak/link_spec.rb",
     "spec/riak/map_reduce_spec.rb",
     "spec/riak/headers_spec.rb",
     "spec/riak/walk_spec_spec.rb",
     "spec/riak/object_spec.rb",
     "spec/riak/net_http_backend_spec.rb",
     "spec/riak/bucket_spec.rb",
     "spec/riak/client_spec.rb",
     "spec/riak/multipart_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2"])
      s.add_development_dependency(%q<rack>, [">= 1.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.2"])
      s.add_development_dependency(%q<curb>, [">= 0.6"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.0.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.3.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.3"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2"])
      s.add_development_dependency(%q<rack>, [">= 1.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.2"])
      s.add_development_dependency(%q<curb>, [">= 0.6"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.0.2"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.3.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3"])
      s.add_dependency(%q<fakeweb>, [">= 1.2"])
      s.add_dependency(%q<rack>, [">= 1.0"])
      s.add_dependency(%q<yard>, [">= 0.5.2"])
      s.add_dependency(%q<curb>, [">= 0.6"])
      s.add_dependency(%q<activesupport>, [">= 2.0.2"])
      s.add_dependency(%q<i18n>, [">= 0.3.3"])
      s.add_dependency(%q<rspec>, [">= 1.3"])
      s.add_dependency(%q<fakeweb>, [">= 1.2"])
      s.add_dependency(%q<rack>, [">= 1.0"])
      s.add_dependency(%q<yard>, [">= 0.5.2"])
      s.add_dependency(%q<curb>, [">= 0.6"])
      s.add_dependency(%q<activesupport>, [">= 2.0.2"])
      s.add_dependency(%q<i18n>, [">= 0.3.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3"])
    s.add_dependency(%q<fakeweb>, [">= 1.2"])
    s.add_dependency(%q<rack>, [">= 1.0"])
    s.add_dependency(%q<yard>, [">= 0.5.2"])
    s.add_dependency(%q<curb>, [">= 0.6"])
    s.add_dependency(%q<activesupport>, [">= 2.0.2"])
    s.add_dependency(%q<i18n>, [">= 0.3.3"])
    s.add_dependency(%q<rspec>, [">= 1.3"])
    s.add_dependency(%q<fakeweb>, [">= 1.2"])
    s.add_dependency(%q<rack>, [">= 1.0"])
    s.add_dependency(%q<yard>, [">= 0.5.2"])
    s.add_dependency(%q<curb>, [">= 0.6"])
    s.add_dependency(%q<activesupport>, [">= 2.0.2"])
    s.add_dependency(%q<i18n>, [">= 0.3.3"])
  end
end

